JAVA=java
JAVAC=javac

default: run

run : program

program : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java test1.txt true
		rm -f mxg200078/*.class

401 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/401.txt true
		rm -f mxg200078/*.class

402 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/402.txt true
		rm -f mxg200078/*.class

403 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/403.txt true
		rm -f mxg200078/*.class

404 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/404.txt true
		rm -f mxg200078/*.class

405 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/405.txt true
		rm -f mxg200078/*.class
406 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/406.txt true
		rm -f mxg200078/*.class
407 : 
		$(JAVAC) mxg200078/MDSDriver.java
		$(JAVA) mxg200078/MDSDriver.java MDSTEST/407.txt true > output.txt
		rm -f mxg200078/*.class
clean:
		rm -f mxg200078/*.class